[package]

name = "hello_world"
version = "0.0.1"
authors = [ "Your name <you@example.com>" ]

[[bin]]
name = "hello_world"
path = "src/hello_world/hello_world.rs"

[[bin]]
name = "module_sample"
path = "src/modules/module_sample.rs"