[package]
name = "rust-training"
version = "0.0.1"
authors = [
	"Nico Orru <nigu.orru@gmail.com>"
]

[[bin]]
name = "hello_world"
path = "src/hello_world/hello_world.rs"

[[bin]]
name = "module_sample"
path = "src/modules/modules.rs"